# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backdrop < Formula
  desc "CLI tool that fills transparent image backgrounds with a solid color"
  homepage "https://github.com/josepmedialdea/backdrop"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josepmedialdea/backdrop/releases/download/v0.2.0/backdrop_darwin_amd64.tar.gz"
      sha256 "bdf5dea5a1b7ab1003cc4f37019c80aa53c2ab729fd46dc81aa4ec186dd0a417"

      define_method(:install) do
        bin.install "backdrop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josepmedialdea/backdrop/releases/download/v0.2.0/backdrop_darwin_arm64.tar.gz"
      sha256 "88577e7decf686c2075134719ca1bd41c3a653a82d55a305ba2f7b2761445722"

      define_method(:install) do
        bin.install "backdrop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josepmedialdea/backdrop/releases/download/v0.2.0/backdrop_linux_amd64.tar.gz"
      sha256 "1fb95f9b2026575669305ff48ed2a2eb8c1de43245ced3b80e3a044999794daa"
      define_method(:install) do
        bin.install "backdrop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josepmedialdea/backdrop/releases/download/v0.2.0/backdrop_linux_arm64.tar.gz"
      sha256 "780d2cd4576635e856017034afa47c1face1491685eb30bebf32ec845e418d09"
      define_method(:install) do
        bin.install "backdrop"
      end
    end
  end
end
