# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backdrop < Formula
  desc "CLI tool that fills transparent image backgrounds with a solid color"
  homepage "https://github.com/josepmedialdea/backdrop"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josepmedialdea/backdrop/releases/download/v0.2.0/backdrop_darwin_amd64.tar.gz"
      sha256 "139c07c54484a6ede82cb2edb981f3e330dba85cf08b4e34868edb444ef28311"

      define_method(:install) do
        bin.install "backdrop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josepmedialdea/backdrop/releases/download/v0.2.0/backdrop_darwin_arm64.tar.gz"
      sha256 "60a8efdffd56d1f3fea1566c44256e0f755d4222a76f09eee07111017da21deb"

      define_method(:install) do
        bin.install "backdrop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josepmedialdea/backdrop/releases/download/v0.2.0/backdrop_linux_amd64.tar.gz"
      sha256 "6d8c7c3e92f368a12eca74faf837e72ea8ba3ac2ac2ed4b36474cf7bbc3dac0a"
      define_method(:install) do
        bin.install "backdrop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josepmedialdea/backdrop/releases/download/v0.2.0/backdrop_linux_arm64.tar.gz"
      sha256 "4cad5ac799f0821a64fe55384f1648a79496ace0364b5c37fa954993b8f7bc20"
      define_method(:install) do
        bin.install "backdrop"
      end
    end
  end

  test do
    system "#{bin}/backdrop", "--help"
  end
end
